#!/bin/dash

pushy_dir=".pushy"

if [ -d "$pushy_dir" ]; then
    echo "pushy-init: error: .pushy already exists"
    exit 1
fi

#initialized the file structure
mkdir -p "$pushy_dir/objects/commits"
mkdir -p "$pushy_dir/refs/heads"
touch "$pushy_dir/index"
touch "$pushy_dir/HEAD"

echo "Initialized empty pushy repository in $pushy_dir"

exit 0